# The URL the site will be built for
base_url = "https://vala.dev"

# The site title and description; used in feeds by default.
title = "Vala Programming Language"
description = "Vala is an object-oriented programming language with a self-hosting compiler that generates C code and uses the GObject type system."

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

# The filename to use for the feed. Used as the template filename, too.
# Defaults to "atom.xml", which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filename = "atom.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
extra_syntaxes_and_themes = ["syntaxes"]

highlight_code = true

highlight_theme = "css"

highlight_themes_css = [
  { theme = "OneHalfLight", filename = "css/syntax-theme-light.css" },
  { theme = "OneHalfDark", filename = "css/syntax-theme-dark.css" },
]

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => üòÑ)
render_emoji = true


# Optional translation object for the default language
# Example:
#     default_language = "fr"
#
#     [translations]
#     title = "Un titre"
#
[translations]
bypass_block = "Skip to main content"
home = "Home"
about = "About"
blog = "Blog"
documentation = "Docs"
community = "Community"
source_code = "Source Code"
wiki = "Wiki"
tagline = "A Familiar Way To Develop Applications"
get_started = "Get Started"
view_source_code = "View Source Code"
why_vala = "Why Vala?"

productivity = "Productivity"
productivity_description = 'Comfortably write your code in an object-oriented way with high level abstractions, while having access to deep integrations with <a href="https://www.gnome.org">GNOME</a> technolgies such as: <a href="https://docs.gtk.org/gobject/">GObject</a>, <a href="https://www.gtk.org">GTK</a> and more!'

performance = "Performance"
performance_description = "Vala compiles code down to blazingly fast, fully native binaries. You're also able to reuse existing C Code in your Vala programs as well as generate C Code from Vala."

open_source = "Open-Source"
open_source_description = "Vala is free and open-source software. It has a great community that contributes to the compiler and develops lots of tooling."
tooling_documentation = "Tooling Documentation"

learn_more_about_vala = "Learn more about Vala"
what_can_you_build = "What can you build?"

gui_applications = "GUI Applications"
gui_applications_description = "Perfect integration of GTK, Libadwaita and Granite makes development super simple. Publish easily your apps on Flathub without bloated packages."
gnome_tutorial = "GNOME Getting Started Tutorial"
elementary_tutorial = "elementary OS App Tutorial"

command_line_programs = "Command Line Programs"
command_line_programs_description = "Use a large standard library and use loads of other libraries available for use in Vala."

libraries = "Libraries"
libraries_description = "Provide bindings for many other languages and API documentation without manual work. Also, dynamic and static linking are both supported."

whats_new = "What's new?"
view_blog = "View Blog"

showcase = "Showcase"
view_more_vala_projects = "View More Vala Projects"

forums = "Forums"
forums_description = "Ask questions related to Vala in the GNOME Discourse forums under the 'vala' tag."
discourse_forums = "Discourse Forums"

internals_chat = "Internals Chat"
internals_chat_description = "Talk to the developers or ask questions about how to contribute to Vala, use the Vala Matrix channel. It also has a IRC bridge."
matrix_room = "Matrix Room"

community_server = "Community Server"
community_server_description = "Connect with the community on the Discord server."
discord_server = "Discord Server"

social_media = "Social Media"
follow_vala_project = "Follow the Vala project across these platforms"
made_by_vala_community = "Made by the Vala Community"
view_website_source_code = "View The Website's Source Code"

languages = "Languages:"
license_description = "This work is licensed under a"

default_image_description = "Purple background with white text on center that says 'Vala'."

page_not_found = "Error 404 - Page Not Found"
page_not_found_description = "The URL may be misspelled or the page you requested no longer exists."
go_home = "Go Home"


# Additional languages definition
# You can define language specific config values and translations:
# title, description, generate_feed, feed_filename, taxonomies, build_search_index
# as well as its own search configuration and translations (see above for details on those)
[languages]

[languages.cs]
generate_feed = true # there will be a feed for Czech content
build_search_index = false # FIXME: cs not supported by Zola

[languages.cs.translations]
bypass_block = "P≈ôej√≠t k hlavn√≠mu obsahu"
home = "Dom≈Ø"
about = "O jazyce"
blog = "Blog"
documentation = "Dokumentace"
community = "Komunita"
source_code = "Zdrojov√Ω k√≥d"
wiki = "Wiki"
tagline = "Zn√°m√Ω zp≈Øsob v√Ωvoje aplikac√≠"
get_started = "Zaƒç√≠t"
view_source_code = "Zobrazit zdrojov√Ω k√≥d"
why_vala = "Proƒç Vala?"

productivity = "Produktivita"
productivity_description = 'M≈Ø≈æete pohodlnƒõ ps√°t k√≥d objektovƒõ orientovan√Ωm zp≈Øsobem s abstrakcemi na vysok√© √∫rovni a z√°rove≈à m√≠t p≈ô√≠stup k hlubok√© integraci s technologiemi <a href="https://www.gnome.org">GNOME</a>, jako <a href="https://docs.gtk.org/gobject/">GObject</a>, <a href="https://www.gtk.org">GTK</a> a dal≈°√≠!'

performance = "V√Ωkon"
performance_description = "Vala zkompiluje k√≥d na bleskurychl√©, plnƒõ nativn√≠ bin√°rn√≠ soubory. V programech Vala m≈Ø≈æete tak√© znovu pou≈æ√≠t existuj√≠c√≠ k√≥d C a generovat k√≥d C z programu Vala."

open_source = "Open-Source"
open_source_description = "Vala je svobodn√Ω software s otev≈ôen√Ωm zdrojov√Ωm k√≥dem. M√° skvƒõlou komunitu, kter√° do kompil√°toru p≈ôisp√≠v√° a vyv√≠j√≠ spoustu n√°stroj≈Ø."
tooling_documentation = "Dokumentace k n√°stroj≈Øm"

learn_more_about_vala = "Zjistƒõte v√≠ce o jazyce Vala"
what_can_you_build = "Co v≈°echno m≈Ø≈æete vytvo≈ôit?"

gui_applications = "Grafick√© aplikace"
gui_applications_description = "D√≠ky dokonal√© integraci GTK, Libadwaita a Granite je v√Ωvoj velmi jednoduch√Ω. Snadno publikujte sv√© aplikace na Flathubu bez zbyteƒçnƒõ velk√Ωch bal√≠ƒçk≈Ø."
gnome_tutorial = "√övodn√≠ kurz GNOME"
elementary_tutorial = "Kurz aplikac√≠ elementary OS"

command_line_programs = "Konzolov√© programy"
command_line_programs_description = "Pou≈æ√≠vejte rozs√°hlou standardn√≠ knihovnu a spoustu dal≈°√≠ch knihoven, kter√© jsou k dispozici pro pou≈æit√≠ ve Vale."

libraries = "Knihovny"
libraries_description = "Vala poskytuje vazby pro mnoho dal≈°√≠ch jazyk≈Ø a dokumentace API bez ruƒçn√≠ pr√°ce. Podporov√°no je tak√© dynamick√© i statick√© linkov√°n√≠."

whats_new = "Co je nov√©ho?"
view_blog = "Zobrazit Blog"

showcase = "Uk√°zka projekt≈Ø"
view_more_vala_projects = "Zobrazit dal≈°√≠ projekty ve Vale"

forums = "F√≥ra"
forums_description = "Ptejte se na ot√°zky t√Ωkaj√≠c√≠ se Valy ve f√≥ru GNOME Discourse pod tagem ‚Äûvala‚Äú."
discourse_forums = "F√≥ra Discourse"

internals_chat = "Intern√≠ chat"
internals_chat_description = "Popov√≠dejte si s v√Ωvoj√°≈ôi nebo se zeptejte na to, jak p≈ôispƒõt do Valy, v Matrix kan√°lu Valy. K dispozici je tak√© most na IRC."
matrix_room = "M√≠stnost na Matrixu"

community_server = "Komunitn√≠ server"
community_server_description = "Spojte se s komunitou na Discord serveru."
discord_server = "Discord server"

social_media = "Soci√°ln√≠ s√≠tƒõ"
follow_vala_project = "Sledujte projekt Vala na tƒõchto platform√°ch"
made_by_vala_community = "Vytvo≈ôeno komunitou jazyka Vala"
view_website_source_code = "Zobrazit zdrojov√Ω k√≥d webu"

languages = "Jazyky:"
license_description = "Tato pr√°ce je licencov√°na pod"

default_image_description = 'Fialov√© pozad√≠ s b√≠l√Ωm textem uprost≈ôed s n√°pisem "Vala".'

page_not_found = "Chyba 404 - Str√°nka nenalezena"
page_not_found_description = "Adresa URL m≈Ø≈æe b√Ωt chybnƒõ zad√°na nebo po≈æadovan√° str√°nka ji≈æ neexistuje."
go_home = "P≈ôej√≠t dom≈Ø"

[languages.fr]
generate_feed = true # there will be a feed for French content
build_search_index = true

[languages.fr.translations]
bypass_block = "Menu principal"
home = "Home"
about = "A propos"
blog = "Blog"
documentation = "Docs"
community = "Community"
source_code = "Le code source"
wiki = "Wiki"
tagline = "A Familiar Way To Develop Applications"
get_started = "Commencer"
view_source_code = "Afficher le code source"
why_vala = "Pourquoi Vala?"

productivity = "Productivit√©"
productivity_description = '√âcrivez confortablement votre code de mani√®re orient√©e objet avec des abstractions de haut niveau, tout en ayant acc√®s √† des int√©grations profondes avec les technologies <a href="https://www.gnome.org">GNOME</a> telles que : <a href="https://docs.gtk.org/gobject/">GObject</a>, <a href="https://www.gtk.org">GTK</a> et plus encore !'

performance = "Performance"
performance_description = "Vala compile le code jusqu'√† des binaires enti√®rement natifs extr√™mement rapides. Vous pouvez √©galement r√©utiliser le code C existant dans vos programmes Vala ainsi que g√©n√©rer du code C √† partir de Vala."

open_source = "Open-Source"
open_source_description = "Vala est un logiciel gratuit et open-source. Il a une grande communaut√© qui contribue au compilateur et d√©veloppe de nombreux outils."
tooling_documentation = "Documentation des outils vala"

learn_more_about_vala = "En savoir plus sur Vala"
what_can_you_build = "Que voulez-vous coder ?"

gui_applications = "Applications Graphique"
gui_applications_description = "L'int√©gration parfaite de GTK, Libadwaita et Granite rend le d√©veloppement super simple. Publiez facilement vos applications sur Flathub sans paquets trop lourd."
gnome_tutorial = "tutoriel de GNOME"
elementary_tutorial = "tutoriel d'elementary OS"

command_line_programs = "Programmes CLI/TUI"
command_line_programs_description = "Utilisez une grande biblioth√®que standard et utilisez des charges d'autres biblioth√®ques disponibles pour une utilisation dans Vala."

libraries = "Librairies"
libraries_description = "Fournir des liaisons pour d'autres langages et de la documentation API sans travail manuel. Ainsi que les liaisons dynamiques et statiques des libs sont prises en charge"

whats_new = "Quoi de neuf?"
view_blog = "Blog"

showcase = "Vitrine"
view_more_vala_projects = "Voir plus de projets Vala"

forums = "Forums"
forums_description = "Posez des questions relatives √† Vala dans les forums GNOME sous l'etiquette vala"
discourse_forums = "Discourse Forums"

internals_chat = "Internals Chat"
internals_chat_description = "Parlez aux d√©veloppeurs ou posez des questions sur la fa√ßon de contribuer √† Vala, utilisez le canal Vala Matrix. Il dispose √©galement d'un canal IRC."
matrix_room = "Canal Matrix"

community_server = "Serveur communautaire"
community_server_description = "Connectez-vous avec la communaut√© sur le serveur Discord."
discord_server = "Discord Serveur"

social_media = "R√©seau sociaux"
follow_vala_project = "Suivez le projet Vala sur ces plateformes"
made_by_vala_community = "Site web communautaire"
view_website_source_code = "Code souce du site"

languages = "Langues:"
license_description = "Ce site est sous licence:"

default_image_description = "un fond violet avec du texte blanc centr√© c'est sign√© 'Vala'."

page_not_found = "Erreur 404 - Page non trouv√©"
page_not_found_description = "la page que vous avez demand√©e n'existe plus."
go_home = "Go Home"

[languages.ru]
generate_feed = true # there will be a feed for French content
build_search_index = true

[languages.ru.translations]
bypass_block = "–û—Å–Ω–æ–≤–Ω–æ–µ –º–µ–Ω—é"
home = "–ì–ª–∞–≤–Ω–∞—è"
about = "–û –Ω–∞—Å"
blog = "–ë–ª–æ–≥"
documentation = "–î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è"
community = "–°–æ–æ–±—â–µ—Å—Ç–≤–æ"
source_code = "–ò—Å—Ö–æ–¥–Ω—ã–π –∫–æ–¥"
wiki = "–í–∏–∫–∏"
tagline = "–ó–Ω–∞–∫–æ–º—ã–π —Å–ø–æ—Å–æ–± —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–∏ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–π"
get_started = "–ù–∞—á–∞—Ç—å"
view_source_code = "–ü–æ–∫–∞–∑–∞—Ç—å –∏—Å—Ö–æ–¥–Ω—ã–π –∫–æ–¥"
why_vala = "–ü–æ—á–µ–º—É Vala?"

productivity = "–ü—Ä–æ–∏–∑–≤–æ–¥–∏—Ç–µ–ª—å–Ω—ã–π"
productivity_description = '–£–¥–æ–±–Ω–æ –ø–∏—à–∏—Ç–µ —Å–≤–æ–π –æ–±—ä–µ–∫—Ç–Ω–æ-–æ—Ä–∏–µ–Ω—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã–π –∫–æ–¥ —Å –≤—ã—Å–æ–∫–æ—É—Ä–æ–≤–Ω–µ–≤—ã–º–∏ –∞–±—Å—Ç—Ä–∞–∫—Ü–∏—è–º–∏, –∏–º–µ—è –ø—Ä–∏ —ç—Ç–æ–º –≥–ª—É–±–æ–∫—É—é –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏—é —Å —Ç–µ—Ö–Ω–æ–ª–æ–≥–∏—è–º–∏ <a href="https://www.gnome.org">GNOME</a>, —ç—Ç–æ —Ç–∞–∫–∏–µ –∫–∞–∫: <a href="https://docs.gtk.org/gobject/">GObject</a> –∏ <a href="https://www.gtk.org">GTK</a>!'

performance = "–≠—Ñ—Ñ–µ–∫—Ç–∏–≤–Ω—ã–π"
performance_description = "Vala –∫–æ–º–ø–∏–ª–∏—Ä—É–µ—Ç—Å—è –≤ –Ω–µ–≤–µ—Ä–æ—è—Ç–Ω–æ –±—ã—Å—Ç—Ä—ã–µ –ø–æ–ª–Ω–æ—Å—Ç—å—é –Ω–∞—Ç–∏–≤–Ω—ã–µ –¥–≤–æ–∏—á–Ω—ã–µ —Ñ–∞–π–ª—ã. –í—ã —Ç–∞–∫–∂–µ –º–æ–∂–µ—Ç–µ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å —Å—É—â–µ—Å—Ç–≤—É—é—â–∏–π C–∏-–∫–æ–¥ –≤ —Å–≤–æ–∏—Ö –ø—Ä–æ–≥—Ä–∞–º–º–∞—Ö Vala, –∞ —Ç–∞–∫–∂–µ –≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞—Ç—å C–∏-–∫–æ–¥ –∏–∑ Vala."

open_source = "–° –æ—Ç–∫—Ä—ã—Ç—ã–º –∫–æ–¥–æ–º"
open_source_description = "Vala - —ç—Ç–æ –±–µ—Å–ø–ª–∞—Ç–Ω–æ–µ –∏ –æ—Ç–∫—Ä—ã—Ç–æ–µ –ø—Ä–æ–≥—Ä–∞–º–º–Ω–æ–µ –æ–±–µ—Å–ø–µ—á–µ–Ω–∏–µ —Å –æ—Ç–ª–∏—á–Ω—ã–º —Å–æ–æ–±—â–µ—Å—Ç–≤–æ–º, –∫–æ—Ç–æ—Ä–æ–µ –≤–Ω–æ—Å–∏—Ç —Å–≤–æ–π –≤–∫–ª–∞–¥ –≤ –∫–æ–º–ø–∏–ª—è—Ç–æ—Ä –∏ —Ä–∞–∑—Ä–∞–±–∞—Ç—ã–≤–∞–µ—Ç –º–Ω–æ–∂–µ—Å—Ç–≤–æ —É–¥–æ–±–Ω—ã—Ö –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç–æ–≤."
tooling_documentation = "–î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç–∞—Ä–∏—è"

learn_more_about_vala = "–£–∑–Ω–∞–π—Ç–µ –±–æ–ª—å—à–µ –æ Vala"
what_can_you_build = "–ß—Ç–æ –≤—ã –º–æ–∂–µ—Ç–µ —Å–¥–µ–ª–∞—Ç—å?"

gui_applications = "–ì—Ä–∞—Ñ–∏—á–µ—Å–∫–∏–µ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è"
gui_applications_description = "–ò–¥–µ–∞–ª—å–Ω–∞—è –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏—è —Å GTK, Libadwaita –∏ Granite –¥–µ–ª–∞–µ—Ç —Ä–∞–∑—Ä–∞–±–æ—Ç–∫—É –æ—á–µ–Ω—å –ø—Ä–æ—Å—Ç–æ–π. –¢–∞–∫ –∂–µ —Å –ª–µ–≥–∫–æ—Å—Ç—å—é –ø—É–±–ª–∏–∫—É–π—Ç–µ —Å–≤–æ–∏ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è –≤–æ Flathub –±–µ–∑ –ª–∏—à–Ω–∏—Ö —Ö–ª–æ–ø–æ—Ç."
gnome_tutorial = "–†—É–∫–æ–≤–æ–¥—Å—Ç–≤–æ GNOME"
elementary_tutorial = "–†—É–∫–æ–≤–æ–¥—Å—Ç–≤–æ elementary OS"

command_line_programs = "–ö–æ–Ω—Å–æ–ª—å–Ω—ã–µ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è"
command_line_programs_description = "–ò—Å–ø–æ–ª—å–∑—É–π—Ç–µ –æ–≥—Ä–æ–º–Ω—É—é —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—É—é –±–∏–±–ª–∏–æ—Ç–µ–∫—É –∏ –º–Ω–æ–∂–µ—Å—Ç–≤–æ –¥—Ä—É–≥–∏—Ö –±–∏–±–ª–∏–æ—Ç–µ–∫, –¥–æ—Å—Ç—É–ø–Ω—ã—Ö –¥–ª—è –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è –≤ Vala."

libraries = "–ë–∏–±–ª–∏–æ—Ç–µ–∫–∏"
libraries_description = "–ü—Ä–µ–¥–æ—Å—Ç–∞–≤–ª—è–π—Ç–µ –ø—Ä–∏–≤—è–∑–∫–∏ –¥–ª—è –±–æ–ª—å—à–∏–Ω—Å—Ç–≤–∞ —è–∑—ã–∫–æ–≤ –∏ –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—é –ø–æ API –±–µ–∑ —Ä—É—á–Ω–æ–π —Ä–∞–±–æ—Ç—ã. –ö—Ä–æ–º–µ —Ç–æ–≥–æ, –ø–æ–¥–¥–µ—Ä–∂–∏–≤–∞—é—Ç—Å—è –∫–∞–∫ –¥–∏–Ω–∞–º–∏—á–µ—Å–∫–∏–µ, —Ç–∞–∫ –∏ —Å—Ç–∞—Ç–∏—á–µ—Å–∫–∏–µ –ø—Ä–∏–≤—è–∑–∫–∏."

whats_new = "–ß—Ç–æ –Ω–æ–≤–æ–≥–æ?"
view_blog = "–ë–ª–æ–≥"

showcase = "–î–µ–º–æ–Ω—Å—Ç—Ä–∞—Ü–∏—è"
view_more_vala_projects = "–ü–æ–∫–∞–∑–∞—Ç—å –±–æ–ª—å—à–µ Vala –ø—Ä–æ–µ–∫—Ç–æ–≤"

forums = "–§–æ—Ä—É–º"
forums_description = "–ó–∞–¥–∞–≤–∞–π—Ç–µ –≤–æ–ø—Ä–æ—Å—ã, —Å–≤—è–∑–∞–Ω–Ω—ã–µ —Å Vala, –Ω–∞ —Ñ–æ—Ä—É–º–∞—Ö GNOME Discourse –ø–æ–¥ —Ç–µ–≥–æ–º ‚Äûvala‚Äú."
discourse_forums = "Discourse –§–æ—Ä—É–º"

internals_chat = "–í–Ω—É—Ç—Ä–µ–Ω–Ω–∏–π —á–∞—Ç"
internals_chat_description = "–û–±—Ä–∞—â–∞–π—Ç–µ—Å—å –∫ —Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫–∞–º –∏–ª–∏ –∑–∞–¥–∞–π—Ç–µ –≤–æ–ø—Ä–æ—Å—ã –æ —Ç–æ–º, –∫–∞–∫ –≤–Ω–µ—Å—Ç–∏ —Å–≤–æ–π –≤–∫–ª–∞–¥ –≤ Vala. –£ –Ω–∞—Å —Ç–∞–∫–∂–µ –µ—Å—Ç—å IRC-—Å–µ—Ä–≤–µ—Ä."
matrix_room = "–ß–∞—Ç Matrix"

community_server = "–°–µ—Ä–≤–µ—Ä —Å–æ–æ–±—â–µ—Å—Ç–≤–∞"
community_server_description = "–ü—Ä–∏—Å–æ–µ–¥–∏–Ω—è–π—Ç–µ—Å—å –∫ —Å–æ–æ–±—â–µ—Å—Ç–≤—É Vala –Ω–∞ Discord —Å–µ—Ä–≤–µ—Ä–µ"
discord_server = "–°–µ—Ä–≤–µ—Ä Discord"

social_media = "–°–æ—Ü–∏–∞–ª—å–Ω—ã–µ —Å–µ—Ç–∏"
follow_vala_project = "–°–ª–µ–¥–∏—Ç–µ –∑–∞ –ø—Ä–æ–µ–∫—Ç–æ–º Vala –Ω–∞ —ç—Ç–∏—Ö –ø–ª–∞—Ç—Ñ–æ—Ä–º–∞—Ö"
made_by_vala_community = "–°–¥–µ–ª–∞–Ω–æ —Å–æ–æ–±—â–µ—Å—Ç–≤–æ–º Vala"
view_website_source_code = "–ü–æ—Å–º–æ—Ç—Ä–µ—Ç—å –∏—Å—Ö–æ–¥–Ω—ã–π –∫–æ–¥ —Å–∞–π—Ç–∞"

languages = "–Ø–∑—ã–∫–∏:"
license_description = "–≠—Ç–æ—Ç —Å–∞–π—Ç –ø–æ–¥ –ª–∏—Ü–µ–Ω–∑–∏–µ–π :"

default_image_description = "–§–∏–æ–ª–µ—Ç–æ–≤—ã–π —Ñ–æ–Ω —Å –±–µ–ª—ã–º —Ç–µ–∫—Å—Ç–æ–º 'Vala' –≤ —Ü–µ–Ω—Ç—Ä–µ"

page_not_found = "–û—à–∏–±–∫–∞ 404 - –°—Ç—Ä–∞–Ω–∏—Ü–∞ –ù–µ –ù–∞–π–¥–µ–Ω–∞"
page_not_found_description = "–í–æ–∑–º–æ–∂–Ω–æ, –≤ URL-–∞–¥—Ä–µ—Å–µ –¥–æ–ø—É—â–µ–Ω–∞ –æ—à–∏–±–∫–∞ –∏–ª–∏ –∑–∞–ø—Ä–æ—à–µ–Ω–Ω–∞—è –≤–∞–º–∏ —Å—Ç—Ä–∞–Ω–∏—Ü–∞ –±–æ–ª—å—à–µ –Ω–µ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç."
go_home = "–ù–∞ –≥–ª–∞–≤–Ω—É—é"

[extra]
# Put all your custom variables here

docs_url="https://wiki.gnome.org/Projects/Vala/Documentation"

tutorial_url = "https://wiki.gnome.org/Projects/Vala/Documentation#Getting_Started"

language_source_code_url = "https://gitlab.gnome.org/GNOME/vala"

site_source_code_url = "https://github.com/vala-lang/vala-www"

license_url = "https://creativecommons.org/licenses/by-sa/4.0/"

wiki_url = "https://wiki.gnome.org/Projects/Vala/"

[extra.features]

gnome_developer_tutorial = "https://developer.gnome.org/documentation/tutorials/beginners/getting_started.html"

elementary_app_tutorial = "https://docs.elementary.io/develop/"


[extra.showcase]

awesome_vala_url = "https://github.com/desiderantes/awesome-vala"

[extra.tooling]

vala_language_server = "https://github.com/vala-lang/vala-language-server"

vala_lint = "https://github.com/vala-lang/vala-lint"

valadoc = "https://wiki.gnome.org/Projects/Valadoc"

gnome_builder = "https://apps.gnome.org/en-GB/app/org.gnome.Builder/"

vs_code = "https://marketplace.visualstudio.com/items?itemName=prince781.vala"

vim = "https://github.com/arrufat/vala.vim"

meson = "https://mesonbuild.com/Vala.html"

documentation = "https://wiki.gnome.org/Projects/Vala/Tools"

[extra.socials]

discourse = "https://discourse.gnome.org/tag/vala"

matrix = "https://matrix.to/#/#_gimpnet_#vala:gnome.org"

mastodon = "https://mastodon.social/@vala_lang"

discord = "https://discord.gg/YFAzjSVHt7"

telegram = "https://t.me/vala_lang"

twitter = "https://www.twitter.com/vala_lang"

reddit = "https://www.reddit.com/r/vala"
